# Project information
site_name: Vivaldi Wiki
site_description: A wiki from Sopranos
site_author: 
site_url: https://wiki.vivalditips.com/en/latest/

# Repository
repo_name: GitHub
repo_url: https://github.com/vivalditurkiye/wiki
remote_branch: master

# Copyright
copyright: The content of this site is licensed under the GNU GPLv3.

# Documentation and theme
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Droid Sans'
    code: 'Droid Sans Mono'
  logo: images/logo.png
  favicon: images/logo.png
  author:
    github: vivalditurkiye
    twitter: vivaldibrowser
  search:
    language: 'en'
extra:
  search:
    tokenizer: '[\s\-\.]+'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - smarty
  - tables
  - toc:
      permalink: '⚓'
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
